version: "3"
services:
  web:
    image: rooharrigan/api-testing:part1b
    ports:
      - "4000:3000"
    depends_on:
      - db
    environment:
      MYSQL_USER: root
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mutiny
  db:
    image: mysql:5
    ports:
      - "3306:3306"
    volumes:
      - "/home/docker/data:/data"
    restart: always
        environment:
      MYSQL_USER: root
      MYSQL_HOST: localhost
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: mutiny
volumes:
  db_data:

